### PR TITLE
Phase2 j query

### PR DESCRIPTION
**Pull request by cxoltero**
On this part of the project, when i use the lightbox class, my pictures appear to be one on top of the other. Other than that, the functionality is there.

### CODE REVIEW

**Comment by paul-barry-kenzan** [comment]
@obuckley-kenzan @cxoltero 
I think review of this PR should be postponed until the `.gitignore` is resolved. Then a rebase will resolve the amount of files changed. `bower_components` and `.idea` are both unnecessary. Just be sure to include the `bower.json` and you'll be good.

**Comment by ghost** [comment]
@paul-barry-kenzan 
Agreed, thought i was posting on #1.  

Yes @cxoltero , I would only recommend working on set of work at a time, so that way feedback get's carried over into the follow up.

**Comment by cxoltero** [comment]
Unnecessary folders have been deleted.

**Comment by paul-barry-kenzan** [comment]
@cxoltero 
An update to `.gitignore` should be made to remove `.DS_Store` files

**Comment by paul-barry-kenzan** [comment]
@cxoltero 
I see the gitignore has been updated, but the `.DS_Store` files are still part of the commit. Please remove those files.

**Comment by ghost** [comment]
@cxoltero / @paul-barry-kenzan 
Let's shut down these PRs for now, because I specifically want to build this up one phase at a time.  I would prefer we step through each phase, make sure the lesson is learned, then move to the next.  Please focus on making PR #2 the best it can be first.

**Pull request closed without merging**
